[project]
name = "reditdataengineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "apache-airflow>=3.1.6",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "praw>=7.8.1",
]
